### ISSUE TITLE
Extend highlight pattern to support finding a child by hierarchy

### ISSUE THREAD

**Issue by cgalvan** [cgalvan/InteractiveTutorials#21]
Currently we are using the `pyside_utils.find_child_by_pattern` API to find the widget/item to highlight for the current step. This works for many cases, but there are a lot of widgets that don't have objectNames set, or are nested with many widgets of the same type. For some of these widgets we can and should give them an appropriate objectName, since this would aid automated testing as well, but for others it might be better to be able to find them a different way.

So, we should extend support to be able to use the `pyside_utils.find_child_by_hierarchy` as well.

@micronAMZN

**Comment by micronAMZN** [comment]
Done: https://github.com/cgalvan/InteractiveTutorials/pull/34
